/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGAffineTransform {
    float a;
    float b;
    float c;
    float d;
    float tx;
    float ty;
};

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct SBProcessTimes {
    double execTime;
    double beginUserCPUElapsedTime;
    double beginSystemCPUElapsedTime;
    double beginIdleCPUElapsedTime;
    double beginApplicationCPUElapsedTime;
};

struct UIEdgeInsets {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct UIPeripheralAnimationGeometry {
    struct CGPoint _field1;
    struct CGPoint _field2;
    struct CGRect _field3;
    struct CGAffineTransform _field4;
    float _field5;
};

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _opaque_pthread_mutex_t {
    long __sig;
    char __opaque[40];
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned char voicemailAvailable;
    int voicemailCount;
    long long voicemailID;
} CDStruct_2a99e736;

typedef struct {
    unsigned int _field1[8];
} CDStruct_6ad76789;

typedef struct {
    char _field1;
    char _field2;
    char _field3;
    float _field4;
    int _field5;
    float _field6;
} CDStruct_4b8f7d89;

typedef struct {
    float x;
    float y;
    float scale;
    float rotate;
} CDStruct_812d5f7b;

typedef struct {
    int _field1;
    char _field2;
    char _field3;
    char _field4;
    char _field5;
    double _field6;
} CDStruct_79f9e052;

typedef struct {
    int _field1;
    int _field2;
} CDStruct_1ef3fb1f;

typedef struct {
    int type;
    unsigned char pathIndex;
    unsigned char pindex;
    unsigned char pcount;
    struct {
        double timestamp;
        struct CGPoint point;
    } points[15];
} CDStruct_a924d358;

typedef struct {
    int direction;
    struct CGRect rect;
} CDStruct_d18cc6b1;

