/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSTimer;

@interface SBAggregateDCommunicator : NSObject
{
    NSTimer *_periodicFlushTimer;
    NSMutableDictionary *_applicationLastStateTime;
    double _backlightOnStartTime;
    BOOL _backlightOnStartTimeWasOnBattery;
    BOOL _backlightOnStartTimeIsValid;
    double _awakeTimeStart;
    BOOL _awakeTimeStartWasOnBattery;
    BOOL _awakeTimeStartIsValid;
    int _lastConnectionType;
    double _lastConnectionTime;
    BOOL _lastConnectionTimeIsValid;
    double _vpnUsageStartTime;
    BOOL _vpnUsageStartTimeIsValid;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)_installedApplicationsChanged:(id)arg1;
- (void)reportApplicationState:(id)arg1 oldState:(unsigned int)arg2 newState:(unsigned int)arg3;
- (void)reportAppSwitcherActivated;
- (void)_batteryStatusChanged:(id)arg1;
- (void)reportScreenHasDimmed;
- (void)reportScreenHasUndimmed;
- (void)_forceUpdateBacklightTimers;
- (void)reportDeviceHasAwoken;
- (void)reportDeviceWillSleep;
- (void)_forceUpdateAwakeTimers;
- (void)reportCallDuration:(double)arg1 connectionType:(int)arg2;
- (void)reportConnectionTypeChanged;
- (void)_forceUpdateConnectionTypeTimers;
- (void)reportVPNStatusChanged;
- (void)_startVPNConnectionTimer;
- (void)_stopVPNConnectionTimer;
- (void)_forceUpdateVPNConnectionTimer;
- (void)reportDiskUsage;
- (void)reportNANDUsage;
- (void)reportAddressBookSize;
- (void)reportSpringBoardDidLaunch;
- (void)reportCurrentThemalLevel:(int)arg1;
- (void)_forceUpdateAllTimers:(id)arg1;
- (void)synchronousCommit;
- (void)_significantTimeChanged:(id)arg1;

@end

