/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

#import "UITextFieldDelegate-Protocol.h"

@class SBTextDisplayView, UIKeyboard, UINavigationBar, UIPushButton, UIScrollView, UITextField, UIView;

@interface SBAlertInputView : SBSlidingAlertDisplay <UITextFieldDelegate>
{
    UITextField *_inputTextField;
    UIKeyboard *_keyboard;
    SBTextDisplayView *_textDisplay;
    UIScrollView *_scroller;
    UINavigationBar *_bar;
    UIView *_sendingFieldView;
    UIPushButton *_button;
    UIView *_buttonBorderView;
    UIView *_textBorderView;
    BOOL _digitsOnly;
    id _delegate;
    int _minLength;
    int _maxLength;
}

+ (id)newTopBarForInstance:(id)arg1;
+ (id)newBottomBarForInstance:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (void)_adjustScrollerFrame;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)showsDesktopImage;
- (void)setMiddleContentAlpha:(float)arg1;
- (void)setText:(id)arg1;
- (void)alertDisplayWillBecomeVisible;
- (void)setMinLength:(int)arg1;
- (void)setMaxLength:(int)arg1;
- (void)_setNavigationBar:(id)arg1;
- (struct CGRect)_calcSendingFieldFrame;
- (struct CGRect)_calcbottomBarFrame;
- (struct CGRect)_calcKeyboardFrame;
- (struct CGRect)_calcButtonFrame;
- (struct CGRect)_calcTextBorderViewFrame;
- (struct CGRect)_calcInputTextFieldFrame;
- (void)layoutForInterfaceOrientation:(int)arg1;
- (BOOL)textField:(id)arg1 shouldInsertText:(id)arg2 replacingRange:(struct _NSRange)arg3;
- (void)setDigitsOnly:(BOOL)arg1;
- (void)sbAlertInputViewSendClicked:(id)arg1;
- (void)sbAlertInputViewCancelClicked:(id)arg1;
- (id)textField;
- (void)_sendClicked:(id)arg1;
@property(retain) UITextField *inputTextField; // @synthesize inputTextField=_inputTextField;
@property(retain) UIView *textBorderView; // @synthesize textBorderView=_textBorderView;
@property(retain) UIView *buttonBorderView; // @synthesize buttonBorderView=_buttonBorderView;
@property(retain) UIPushButton *button; // @synthesize button=_button;
@property(retain) UIView *sendingFieldView; // @synthesize sendingFieldView=_sendingFieldView;
@property(retain) UIKeyboard *keyboard; // @synthesize keyboard=_keyboard;

@end

