/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIAlertViewDelegate-Protocol.h"

@class UIAlertView;

@interface SBAlertItem : NSObject <UIAlertViewDelegate>
{
    UIAlertView *_alertSheet;
    BOOL _disallowUnlockAction;
    BOOL _orderOverSBAlert;
    BOOL _preventLockOver;
    BOOL _didEverActivate;
    BOOL _didPlayPresentationSound;
}

- (Class)alertSheetClass;
- (id)alertSheet;
- (void)dealloc;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)allowAutoUnlock;
- (BOOL)shouldShowInLockScreen;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)undimsScreen;
- (BOOL)unlocksScreen;
- (BOOL)togglesMediaControls;
- (BOOL)dismissOnLock;
- (BOOL)dismissOnAlertActivation;
- (BOOL)willShowInAwayItems;
- (BOOL)didPlayPresentationSound;
- (void)_playPresentationSound;
- (void)playPresentationSound;
- (void)cleanPreviousConfiguration;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)lockLabel;
- (float)lockLabelFontSize;
- (double)autoDismissInterval;
- (void)setDisallowsUnlockAction:(BOOL)arg1;
- (BOOL)disallowsUnlockAction;
- (void)performUnlockAction;
- (void)setOrderOverSBAlert:(BOOL)arg1;
- (BOOL)preventLockOver;
- (void)setPreventLockOver:(BOOL)arg1;
- (void)willActivate;
- (void)didActivate;
- (void)willRelockForButtonPress:(BOOL)arg1;
- (void)buttonDismissed;
- (void)dismiss;
- (void)dismiss:(int)arg1;
- (void)screenWillUndim;
- (void)willDeactivateForReason:(int)arg1;
- (void)didDeactivateForReason:(int)arg1;
- (void)noteVolumeOrLockPressed;
- (id)awayItem;
- (int)alertItemNotificationType;
- (id)alertItemNotificationDate;
- (id)alertItemNotificationSender;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;

@end

