/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol SBAppPagerDelegate
- (id)appPager:(id)arg1 viewForItem:(id)arg2;

@optional
- (void)appPagerFinishedScrolling:(id)arg1;
@end

