/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class CALayer, NSTimer, SBApplication;

@interface SBAppToAppTransitionView : UIView
{
    id _delegate;
    SBApplication *_fromApplication;
    SBApplication *_toApplication;
    CALayer *_startLayer;
    CALayer *_stopLayer;
    UIView *_fromView;
    UIView *_toView;
    BOOL _animating;
    int _orientation;
    NSTimer *_timer;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setFromView:(id)arg1;
- (void)setToView:(id)arg1;
- (void)_beginTransition;
- (void)beginTransition;
@property(retain, nonatomic) SBApplication *toApp; // @synthesize toApp=_toApplication;
- (BOOL)isAnimating;
- (void)_animationDidStop:(id)arg1;
- (id)_rotationValueFunction;
- (float)_rotationRadians;
- (void)_transitionBegun:(double)arg1;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) SBApplication *fromApp; // @synthesize fromApp=_fromApplication;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;

@end

