/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray;

@interface SBAppContextHostView : UIView
{
    NSMutableArray *_contexts;
    BOOL _hostingEnabled;
}

- (id)initWithDefaultSize;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)description;
- (void)_setLayerFrameAndTransform:(id)arg1;
- (void)setHostingEnabled:(BOOL)arg1 resetOnDisable:(BOOL)arg2;
@property(nonatomic, getter=isHostingEnabled) BOOL hostingEnabled; // @synthesize hostingEnabled=_hostingEnabled;
@property(readonly, nonatomic) unsigned int count;
- (BOOL)isContextIdHidden:(unsigned int)arg1;
- (void)setContextId:(unsigned int)arg1 hidden:(BOOL)arg2;
- (void)willOrderInContextWithId:(unsigned int)arg1 windowLevel:(float)arg2 windowOutput:(int)arg3;
- (void)didOrderOutContextWithId:(unsigned int)arg1;
- (void)setOrderOutPending:(BOOL)arg1 forContextId:(unsigned int)arg2;
- (void *)createIOSurfaceForFrame:(struct CGRect)arg1;
- (void *)createIOSurfaceForFrame:(struct CGRect)arg1 outTransform:(struct CGAffineTransform *)arg2;
- (void *)createIOSurfaceForFrame:(struct CGRect)arg1 includeAdditionalContext:(unsigned int)arg2 outTransform:(struct CGAffineTransform *)arg3;
- (void *)createIOSurfaceForFrame:(struct CGRect)arg1 includeAdditionalContext:(unsigned int)arg2 usePurpleGfx:(BOOL)arg3 outTransform:(struct CGAffineTransform *)arg4;

@end

