/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, SBAppPagerScrollView, SBPointTracker;

@interface SBAppPager : UIView <UIScrollViewDelegate>
{
    id <SBAppPagerDelegate> m_delegate;
    SBAppPagerScrollView *m_scrollView;
    NSMutableArray *m_pageSubviews;
    NSArray *m_apps;
    int m_currentPage;
    float m_pageWidth;
    float m_pageMargin;
    struct CGPoint m_rawOffset;
    SBPointTracker *m_pointTracker;
    double m_baseDuration;
    double m_startTime;
    double m_scrollAnimationDuration;
    int m_leftViewOrientation;
    int m_middleViewOrientation;
    int m_rightViewOrientation;
    BOOL m_paging;
    BOOL m_pagingCanUnderflow;
    BOOL m_pagingCanOverflow;
    BOOL m_pagingUnderflow;
    BOOL m_pagingOverflow;
    BOOL m_middleWithLeft;
    BOOL m_middleWithRight;
    BOOL m_blockingPageStretchDelegate;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
@property(readonly, nonatomic) id leftApp;
@property(readonly, nonatomic) id middleApp;
@property(readonly, nonatomic) id rightApp;
- (int)pageForContentOffset;
- (struct CGPoint)contentOffsetForPage:(int)arg1;
- (struct CGRect)frameForPage:(int)arg1;
- (id)updateViewForPage:(int)arg1;
- (void)ensureViewsForCurrentPage;
- (void)setPage:(int)arg1;
- (void)setPage:(int)arg1 animated:(BOOL)arg2;
- (void)setApps:(id)arg1 page:(int)arg2;
- (void)beginPaging;
- (void)updatePaging:(float)arg1;
- (void)finishPaging;
- (void)cancelPaging;
- (void)stretchViewAnimatedEnded:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
@property(readonly, nonatomic) BOOL middleWithRight; // @synthesize middleWithRight=m_middleWithRight;
@property(readonly, nonatomic) BOOL middleWithLeft; // @synthesize middleWithLeft=m_middleWithLeft;
@property(readonly, nonatomic) BOOL pagingOverflow; // @synthesize pagingOverflow=m_pagingOverflow;
@property(readonly, nonatomic) BOOL pagingUnderflow; // @synthesize pagingUnderflow=m_pagingUnderflow;
@property(readonly, nonatomic) BOOL paging; // @synthesize paging=m_paging;
@property(readonly, nonatomic) int rightViewOrientation; // @synthesize rightViewOrientation=m_rightViewOrientation;
@property(readonly, nonatomic) int middleViewOrientation; // @synthesize middleViewOrientation=m_middleViewOrientation;
@property(readonly, nonatomic) int leftViewOrientation; // @synthesize leftViewOrientation=m_leftViewOrientation;
@property(readonly, nonatomic) int currentPage; // @synthesize currentPage=m_currentPage;
@property(nonatomic) BOOL pagingCanOverflow; // @synthesize pagingCanOverflow=m_pagingCanOverflow;
@property(nonatomic) BOOL pagingCanUnderflow; // @synthesize pagingCanUnderflow=m_pagingCanUnderflow;
@property(nonatomic) float pageMargin; // @synthesize pageMargin=m_pageMargin;
@property(readonly, nonatomic) NSArray *apps; // @synthesize apps=m_apps;
@property(nonatomic) id delegate; // @synthesize delegate=m_delegate;

@end

