/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class CPDistributedNotificationCenter, NSDictionary, NSLock, NSMutableDictionary, NSMutableSet, NSOperationQueue, NSTimer, SBProcess;

@interface SBApplicationController : NSObject
{
    NSDictionary *_pendingApplicationDictionaries;
    NSMutableDictionary *_applications;
    NSMutableDictionary *_applicationsByBundleIdentifer;
    NSMutableSet *_applicationsUsingLocation;
    NSTimer *_locationIconTimer;
    BOOL _locationIconRemovalPending;
    SBProcess *_processCurrentlyRecordingAudio;
    NSDictionary *_backgroundDisplayDict;
    unsigned int _ignoreUninstallationEventCount;
    CPDistributedNotificationCenter *_appStateNotificationCenter;
    NSOperationQueue *_backgroundOperationQueue;
    NSLock *_applicationsLock;
}

+ (id)_sharedInstanceCreateIfNecessary:(BOOL)arg1;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (id)init;
- (void)dealloc;
- (void)_unregisterForAudioRecordingNotifications;
- (void)_registerForAudioRecordingNotifications;
- (void)_mediaServerConnectionDied:(id)arg1;
- (void)_recordingStateChanged:(id)arg1;
- (void)_registerForAwayControllerDidLockNotification;
- (void)_awayControllerDidLock:(id)arg1;
- (void)_setLocationIconTimer;
- (void)_removeLocationIconTimer;
- (void)_locationIconTimerFired:(id)arg1;
- (BOOL)_locationActiveForAppWithDetails:(id)arg1;
- (void)_updateLocationState;
- (void)buildLocationState;
- (BOOL)appsAreUsingLocation;
- (id)allApplications;
- (id)applicationsWithBundleIdentifier:(id)arg1;
- (id)applicationsWithPid:(int)arg1;
- (id)processWithPid:(int)arg1;
- (id)applicationWithDisplayIdentifier:(id)arg1;
- (id)applicationWithPid:(int)arg1;
- (id)primaryRoleApplicationWithPid:(int)arg1;
- (id)iPod;
- (id)applicationCurrentlyRecordingAudio;
- (id)dataActivation;
- (id)loadApplications;
- (void)loadApplicationsAndIcons:(id)arg1 reveal:(BOOL)arg2 popIn:(BOOL)arg3 reloadAllIcons:(BOOL)arg4;
- (void)removeApplicationsFromModelWithBundleIdentifier:(id)arg1;
- (void)uninstallApplication:(id)arg1;
- (void)waitForOperationsToComplete;
- (Class)applicationClassForBundleIdentifier:(id)arg1;
- (void)loadRolesWithBundle:(id)arg1 bundlePath:(id)arg2 isSystemApplication:(BOOL)arg3 defaultTags:(id)arg4 signerIdentity:(id)arg5 provisioningProfileValidated:(BOOL)arg6 seatbeltEnvironmentVariables:(id)arg7;
- (BOOL)_hasRequiredCapabilities:(id)arg1;
- (void)updateSchemesForRoleDefinition:(id)arg1 displayIdentifier:(id)arg2 application:(id)arg3;
- (id)rolesForInfoPlist:(id)arg1;
- (id)rolesForRoleDefinitions:(id)arg1;
- (id)displayNameForInfoDictionary:(id)arg1 inBundle:(id)arg2 atPath:(id)arg3;
- (id)widgetRoles;
- (void)_applicationInstallationCallback:(id)arg1;
- (void)_handleInstalledApplicationDictionaryIfReceived;
- (void)processPendingInstalls;
- (void)applicationStateChanged:(id)arg1 state:(unsigned int)arg2;
- (void)setApplicationRoles:(id)arg1 withProcess:(id)arg2;
- (void)_reloadBackgroundIDsDict;
- (void)_setSuspendTypeForApp:(id)arg1;
- (void)updateBackgroundAppPrefs;
- (id)_defaultRoleForApplication:(id)arg1;
- (BOOL)aquireInstallationAssertionForDisplayIdentifier:(id)arg1 clientPort:(unsigned int)arg2;
@property(retain) NSDictionary *pendingApplicationDictionaries; // @synthesize pendingApplicationDictionaries=_pendingApplicationDictionaries;

@end

