/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIScrollView.h"

@interface SBAppPagerScrollView : UIScrollView
{
    float m_pageWidth;
    struct CGPoint m_rawOffset;
    float m_maxOffset;
    struct CGPoint m_startingOffset;
    BOOL m_paging;
    BOOL m_moved;
}

@property(nonatomic) BOOL paging; // @synthesize paging=m_paging;
- (void)setContentOffset:(struct CGPoint)arg1;
- (struct CGPoint)_originalOffsetForAnimatedSetContentOffset;
@property(nonatomic) float maxOffset; // @synthesize maxOffset=m_maxOffset;
@property(nonatomic) float pageWidth; // @synthesize pageWidth=m_pageWidth;

@end

