/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "SBAppSwitcherBarViewDelegate-Protocol.h"
#import "SBIconDelegate-Protocol.h"

@class SBAppSwitcherBarView, SBAppSwitcherModel, SBApplicationIcon, SBNowPlayingBar, SBPrintStatusController;

@interface SBAppSwitcherController : NSObject <SBIconDelegate, SBAppSwitcherBarViewDelegate>
{
    SBAppSwitcherModel *_model;
    SBNowPlayingBar *_nowPlayingBar;
    SBAppSwitcherBarView *_bottomBar;
    SBApplicationIcon *_pressedIcon;
    BOOL _editing;
    SBPrintStatusController *_printStatusController;
}

+ (id)sharedInstance;
+ (id)sharedInstanceIfAvailable;
- (id)init;
- (void)dealloc;
- (void)applicationLaunched:(id)arg1;
- (void)applicationDied:(id)arg1;
- (void)applicationSuspended:(id)arg1;
- (void)applicationsRemoved:(id)arg1 andAdded:(id)arg2;
- (void)viewWillAppear;
- (void)viewWillDisappearWithAnimationDuration:(double)arg1;
- (void)downloadsChanged:(id)arg1 withRemovals:(id)arg2;
- (void)downloadItemUpdatingStatusChanged:(id)arg1;
- (id)switcherViewForApp:(id)arg1 orientation:(int)arg2;
- (BOOL)handleMenuButtonTap;
- (BOOL)isScrolling;
- (BOOL)nowPlayingControlsVisible;
- (BOOL)airPlayControlsVisible;
- (id)applicationIconForDisplayIdentifier:(id)arg1;
- (id)_applicationIconsExcept:(id)arg1 forOrientation:(int)arg2;
- (BOOL)_inEditMode;
- (void)_beginEditing;
- (void)_stopEditing;
- (void)_removeApplicationFromRecents:(id)arg1;
- (id)_currentDownloads;
- (id)_currentIcons;
- (id)_iconForApplication:(id)arg1;
- (id)_iconForDownload:(id)arg1;
- (id)_iconForPrinting;
- (void)setNeedsPrintStatusIcon:(BOOL)arg1;
- (void)removePrintStatusIconBadge;
- (void)dismissPrintView;
- (id)printIcon;
- (BOOL)printViewIsShowing;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)iconTapped:(id)arg1;
- (BOOL)iconShouldAllowTap:(id)arg1;
- (void)iconHandleLongPress:(id)arg1;
- (void)iconTouchBegan:(id)arg1;
- (int)closeBoxTypeForIcon:(id)arg1;
- (void)iconCloseBoxTapped:(id)arg1;
- (void)appSwitcherBarRemovedFromSuperview:(id)arg1;
- (BOOL)appSwitcherBar:(id)arg1 scrollShouldCancelInContentForView:(id)arg2;
- (void)appSwitcherBar:(id)arg1 pageAtIndexDidAppear:(int)arg2;
- (void)appSwitcherBar:(id)arg1 pageAtIndexDidDisappear:(int)arg2;
@property(readonly, nonatomic) SBAppSwitcherModel *model; // @synthesize model=_model;

@end

