/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, SBAwayController;

@interface SBAwayModel : NSObject
{
    SBAwayController *_controller;
    NSMutableArray *_standardVMs;
    NSMutableArray *_calls;
    NSMutableArray *_SMSs;
    NSMutableArray *_videoConferences;
    NSMutableArray *_otherAwayItems;
}

+ (BOOL)shouldHideSMSSender;
- (id)initWithController:(id)arg1;
- (void)dealloc;
- (void)clearAwayItems;
- (void)markAwayTime;
- (void)addOtherAwayItem:(id)arg1;
- (void)addCall:(struct __CTCall *)arg1;
- (void)addSMSMessage:(id)arg1;
- (void)addVideoConferenceWithInviter:(id)arg1 atDate:(id)arg2;
- (void)populateWithMissedCalls:(id)arg1;
- (void)populateWithMissedVideoConferences:(id)arg1;
- (void)populateWithMissedSMS:(id)arg1;
- (void)populateWithMissedEnhancedVoiceMails:(id)arg1;
- (id)missedItems;
- (int)uncoalescedMissedItemCount;
- (void)setStandardVoiceMailCount:(int)arg1;

@end

