/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIAlertView.h"

@class NSArray, UIView;

@interface SBAwayItemsView : UIAlertView
{
    UIView *_itemView;
    NSArray *_displayedItems;
    float _widestLabel;
}

- (id)init;
- (void)dealloc;
- (id)itemTitleFont;
- (id)itemLabelFont;
- (void)layout;
- (BOOL)reloadData;
- (id)_labelForAwayItem:(id)arg1 count:(int)arg2;
- (id)_titleForAwayItem:(id)arg1 count:(int)arg2;
- (id)_displayedItems;
- (float)_widestLabel;
- (BOOL)hasAwayItems;

@end

