/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBCallAlert : SBAlert
{
    BOOL _causedSuspension;
    void *_addressBook;
}

+ (void)registerForAlerts;
- (id)initWithCall:(struct __CTCall *)arg1;
- (void)dealloc;
- (void)_handleCallEvent:(struct __CTCall *)arg1;
- (void)_handleCallerIDEvent:(struct __CTCall *)arg1;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;

@end

