/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAwayItem.h"

@interface SBCalendarAwayItem : SBAwayItem
{
    BOOL _isAllDay;
    double _eventDate;
}

- (id)secondTitle;
@property(nonatomic) BOOL isAllDay; // @synthesize isAllDay=_isAllDay;
@property(nonatomic) double eventDate; // @synthesize eventDate=_eventDate;

@end

