/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBCalendarController : NSObject
{
    struct __CFDateFormatter *_dayFormatter;
    struct __CFDateFormatter *_timeFormatter;
    int _unreadInvitationCount;
    struct CalEventExpirationMonitor *_expirationMonitor;
    struct CalAlarmEngine *_alarmEngine;
    struct CalDatabase *_database;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)_finishInitialization;
- (void)_databaseChanged:(id)arg1;
- (void)_unreadInvitationsExpired:(id)arg1;
- (void)_setInvitationUnreadCount:(int)arg1;
- (int)unreadInvitationCount;
- (void)_alertForInvitations;
- (void)_adjustOnWake;
- (void)_didWakeFromSleep;
- (void)_alarmsDidFire:(id)arg1;
- (void)_checkForTimeZoneIfNecessary;
- (void)_significantTimeChange;
- (id)_stringForDay:(CDStruct_79f9e052)arg1 withLongFormatString:(id)arg2 useAbbreviatedFormats:(BOOL)arg3;
- (id)stringForDay:(CDStruct_79f9e052)arg1 withLongFormatString:(id)arg2;
- (id)abbreviatedStringForDay:(CDStruct_79f9e052)arg1 withLongFormatString:(id)arg2;
- (struct __CFDateFormatter *)timeFormatter;
- (id)_dayStringForDate:(double)arg1 allDay:(BOOL)arg2 shortFormat:(BOOL)arg3;
- (id)_timeStringForDate:(double)arg1;
- (id)timeStringForDate:(double)arg1 inTimeZone:(id)arg2;
- (id)dateStringForDate:(double)arg1 allDay:(BOOL)arg2 shortFormat:(BOOL)arg3;
- (void)playAlertSound;

@end

