/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "CNFSoundPlayerDelegateProtocol-Protocol.h"

@class CNFAudioPlayer, CNFConferenceController, NSDate, SBVideoAlert;

@interface SBConferenceManager : NSObject <CNFSoundPlayerDelegateProtocol>
{
    CNFConferenceController *_conferenceController;
    SBVideoAlert *_currentVideoAlert;
    unsigned int _avState;
    unsigned int _endedReason;
    NSDate *_conferenceStartedDate;
    CNFAudioPlayer *_player;
}

+ (id)sharedInstance;
+ (void)initialize;
- (id)init;
@property(readonly) CNFConferenceController *conferenceController;
- (void)alertHasBeenHandled;
- (BOOL)videoConferenceInvitationExists;
- (BOOL)invitationIsFaceTimeUpgrade;
- (BOOL)inConference;
- (BOOL)canStartConference;
- (BOOL)shouldCreateMissedFaceTimeCall;
- (void)answerIncomingConference;
- (void)declineIncomingConference;
- (void)endConference;
- (void)playSound:(int)arg1 numOfLoops:(int)arg2 pauseDuration:(float)arg3;
- (void)stopAudioPlayer;
- (void)dealloc;
- (void)updateStatusBar;
- (void)_updateStatusBar;
- (id)durationString;
- (void)_handleInvitation:(id)arg1;
- (void)_handleMissedInvitation:(id)arg1;
- (void)_conferenceStateChanged:(id)arg1;
- (void)_conferenceAvailabilityChanged:(id)arg1;
- (void)_conferenceCapabilityChanged:(id)arg1;
- (void)audioPlayerDidStopPlaying:(id)arg1;
@property(readonly) unsigned int chatState; // @synthesize chatState=_avState;
@property(readonly) SBVideoAlert *currentVideoAlert; // @synthesize currentVideoAlert=_currentVideoAlert;

@end

