/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

#import "UIKeyInput-Protocol.h"

@class NSString, UIPasscodeField, UITextInputTraits;

@interface SBDeviceLockEntryField : UIView <UIKeyInput>
{
    int _style;
    int _interfaceOrientation;
    UIPasscodeField *_passcodeField;
    UITextInputTraits *_textInputTraits;
    struct __CFCharacterSet *_numericTrimmingSet;
    id _delegate;
}

- (id)initWithStyle:(int)arg1 interfaceOrientation:(int)arg2;
- (void)dealloc;
- (BOOL)canBecomeFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)isFirstResponder;
- (id)passcodeField;
- (struct CGSize)_fieldSizeForCurrentDevice;
- (void)_layoutForCurrentDevice;
@property(nonatomic) int interfaceOrientation; // @synthesize interfaceOrientation=_interfaceOrientation;
@property(copy, nonatomic) NSString *stringValue;
@property(nonatomic, getter=isOkayButtonEnabled) BOOL okayButtonEnabled;
- (void)appendString:(id)arg1;
- (void)deleteLastCharacter;
- (id)textInputTraits;
- (void)passcodeFieldTextDidChange:(id)arg1;
- (BOOL)passcodeField:(id)arg1 shouldInsertText:(id)arg2;
- (void)passcodeFieldDidAcceptEntry:(id)arg1;
- (id)text;
- (void)setText:(id)arg1;
- (BOOL)hasText;
- (void)insertText:(id)arg1;
- (void)deleteBackward;
- (void)forwardInvocation:(id)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;

// Remaining properties
@property(nonatomic) int autocapitalizationType;
@property(nonatomic) int autocorrectionType;
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(nonatomic) int keyboardAppearance;
@property(nonatomic) int keyboardType;
@property(nonatomic) int returnKeyType;
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;

@end

