/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "SSDownloadQueueObserver-Protocol.h"

@class NSMutableSet, SSDownloadQueue;

@interface SBDownloadController : NSObject <SSDownloadQueueObserver>
{
    SSDownloadQueue *_downloadQueue;
    NSMutableSet *_pendingDownloadRemovals;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)_delayedDownloadQueueChange;
- (void)downloadQueue:(id)arg1 changedWithRemovals:(id)arg2;
- (void)downloadQueue:(id)arg1 downloadStatusChangedAtIndex:(int)arg2;
- (void)downloadQueueNetworkUsageChanged:(id)arg1;
- (void)_showDownloadQueueError;
- (void)downloadQueueError:(id)arg1;
- (BOOL)checkQueue;
- (id)currentDownloads;
- (id)downloadQueue;

@end

