/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBLeafIcon.h"

@class NSString, SBDownloadingProgressBar, SSDownload, SSDownloadStatus;

@interface SBDownloadingIcon : SBLeafIcon
{
    NSString *_leafIdentifier;
    NSString *_applicationBundleID;
    SSDownload *_download;
    SBDownloadingProgressBar *_progressView;
    float _progress;
    BOOL _installing;
    BOOL _wasUninstalledByUser;
    SSDownloadStatus *_lastStatus;
}

+ (id)leafIdentifierForDownloadUniqueID:(id)arg1;
+ (id)leafIdentifierForDownload:(id)arg1;
- (id)initWithLeafIdentifier:(id)arg1;
- (id)initWithDownload:(id)arg1;
- (void)dealloc;
- (id)description;
- (void)setLeafIdentifier:(id)arg1;
- (id)identifierForCorrespondingApplicationIcon;
- (id)generateIconImage:(int)arg1;
- (void)setDisplayedIconImage:(id)arg1;
- (void)updateDisplayName;
- (BOOL)shouldEllipsizeLabel;
- (id)displayName;
- (id)_realDisplayName;
- (id)leafIdentifier;
- (void)launch;
- (BOOL)allowsUninstall;
- (void)setGhostly:(BOOL)arg1 requester:(int)arg2;
- (void)completeUninstall;
- (void)reloadForStatusChange;
- (float)progress;
- (id)applicationBundleID;
- (void)setApplicationBundleID:(id)arg1;
- (void)setDownload:(id)arg1;
- (id)download;
- (void)retry;
- (void)remove;
- (BOOL)uninstalledByUser;
- (void)setUninstalledByUser:(BOOL)arg1;
- (id)uninstallAlertTitle;
- (id)uninstallAlertBody;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertCancelTitle;
- (void)_showAlertForError:(id)arg1;
- (void)_thumbnailAvailableNotification:(id)arg1;

@end

