/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIPushButton.h"

@interface SBEmergencyCallButton : UIPushButton
{
}

+ (id)defaultFont;
- (void)drawTitleInRect:(struct CGRect)arg1;
- (void)drawButtonPart:(int)arg1 inRect:(struct CGRect)arg2;

@end

