/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class SBGestureMotionParams;

@interface SBFluidSlideIntegrator : NSObject
{
    SBGestureMotionParams *_motionParams;
    _Bool _fluidityHasBegunOnThisAxis;
    float _swipeDistanceDelta;
    float _filteredSwipeDelta;
    float _cumulativeSwipeDistance;
    float _committedRecentDisplacement;
    float _cumulativeSwipeEnvelope;
    float _relSensitivity[4];
    float _arcCenter;
    float _arcSize;
}

- (void)dealloc;
@property(nonatomic) float translationSensitivity;
@property(nonatomic) float scaleSensitivity;
@property(nonatomic) float rotationSensitivity;
@property(readonly, nonatomic) float swipePercentage;
@property(readonly, nonatomic) float swipePercentageDelta;
@property(readonly, nonatomic) float swipeDistance;
@property(readonly, nonatomic) float swipeDistanceDelta;
@property(readonly, nonatomic) float swipeMomentum;
@property(readonly, nonatomic) float swipeMomentumPercentage;
- (void)clear;
- (float)integratePixelDeltas:(CDStruct_812d5f7b *)arg1 averageVelocities:(CDStruct_812d5f7b *)arg2 farthestFingerSeparation:(float)arg3;
@property(readonly, nonatomic) BOOL hasSignificantMotion;
- (BOOL)hasSufficientMomentumToRecognizeInInterval:(double)arg1;
@property(nonatomic) float arcSize; // @synthesize arcSize=_arcSize;
@property(nonatomic) float arcCenter; // @synthesize arcCenter=_arcCenter;
@property(retain, nonatomic) SBGestureMotionParams *motionParams; // @synthesize motionParams=_motionParams;

@end

