/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBGestureRecognizer.h"

@class SBFluidSlideIntegrator;

@interface SBFluidSlideGestureRecognizer : SBGestureRecognizer
{
    SBFluidSlideIntegrator *m_impl;
    int m_degreeOfFreedom;
    unsigned int m_minTouches;
}

- (id)initWithDegreeOfFreedom:(int)arg1;
- (id)initWithDegreeOfFreedom:(int)arg1 animationDistance:(float)arg2 commitDistance:(float)arg3;
- (id)initWithDegreeOfFreedom:(int)arg1 animationDistance:(float)arg2 commitDistance:(float)arg3 accelerationThreshold:(float)arg4 accelerationPower:(float)arg5 requiredDirectionality:(int)arg6;
- (void)dealloc;
- (BOOL)hasSufficientMomentumToRecognize;
- (BOOL)hasSufficientMomentumToRecognizeInInterval:(double)arg1;
@property(readonly, nonatomic) float cumulativePercentage;
@property(readonly, nonatomic) float incrementalPercentage;
@property(readonly, nonatomic) float cumulativeMovement;
@property(readonly, nonatomic) float incrementalMovement;
@property(readonly, nonatomic) int requiredDirectionality;
- (void)reset;
- (void)updateForBeganOrMovedTouches:(struct __SBGestureContext *)arg1;
- (void)updateForEndedOrCancelledTouches:(struct __SBGestureContext *)arg1;
- (void)updateActiveTouches:(struct __SBGestureContext *)arg1;
- (void)touchesBegan:(struct __SBGestureContext *)arg1;
- (void)touchesMoved:(struct __SBGestureContext *)arg1;
- (void)touchesEnded:(struct __SBGestureContext *)arg1;
- (void)touchesCancelled:(struct __SBGestureContext *)arg1;
@property(nonatomic) unsigned int minTouches; // @synthesize minTouches=m_minTouches;
@property(readonly, nonatomic) int degreeOfFreedom; // @synthesize degreeOfFreedom=m_degreeOfFreedom;

@end

