/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

#import "UITextFieldDelegate-Protocol.h"

@class SBFolder, SBFolderIconListView, SBFolderTextField, SBFolderTitleLabel, SBLinenView, UIImageView;

@interface SBFolderView : UIView <UITextFieldDelegate>
{
    SBFolder *_folder;
    SBFolderTitleLabel *_label;
    SBFolderTextField *_textField;
    SBFolderIconListView *_iconListView;
    SBLinenView *_backgroundView;
    BOOL _isEditing;
    UIImageView *_shadows[10];
    unsigned int _rows;
    CDStruct_d18cc6b1 _notchInfo;
    int _orientation;
}

+ (struct CGSize)boundsSizeForRows:(unsigned int)arg1 orientation:(int)arg2;
+ (struct CGRect)linenRectForRows:(unsigned int)arg1 orientation:(int)arg2;
+ (struct CGRect)linenNotchRectForRows:(unsigned int)arg1 orientation:(int)arg2 notchInfo:(CDStruct_d18cc6b1)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setRows:(unsigned int)arg1 notchInfo:(CDStruct_d18cc6b1)arg2 orientation:(int)arg3;
- (unsigned int)rows;
- (struct CGRect)rectForNotchLinen;
- (void)setIconListView:(id)arg1;
- (void)_placeIconListView;
- (id)iconListView;
- (void)dealloc;
- (void)setFolder:(id)arg1;
- (void)setFolderName:(id)arg1;
- (void)_placeLabelAndTextField;
- (void)setIsEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)enableShiftForFolderTextFieldAfterBeginEditing;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldClear:(id)arg1;
- (struct _NSRange)textField:(id)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)setBackgroundAlpha:(float)arg1;
- (id)editTitleField;
- (id)_shadowForPosition:(int)arg1;
- (void)_placeShadow:(int)arg1;
- (void)_placeShadows;

@end

