/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIcon.h"

@class NSMutableSet, SBDownloadingProgressBar, SBFolder, UIImageView;

@interface SBFolderIcon : SBIcon
{
    SBFolder *_folder;
    UIImageView *_iconBorderView;
    UIImageView *_scrollingIconImageView;
    SBDownloadingProgressBar *_progressBar;
    NSMutableSet *_animatingIcons;
    unsigned int _currentScrollRow;
    BOOL _skippingGridIcons;
}

+ (id)homeScreenIconOverlayImage;
- (id)initWithFolder:(id)arg1;
- (void)dealloc;
- (id)generateIconImage:(int)arg1;
- (void)setIconScrollPosition:(int)arg1 animated:(BOOL)arg2;
- (void)setIsOverlapping:(BOOL)arg1;
- (struct CGRect)rectForMiniIconAtIndex:(unsigned int)arg1;
- (id)croppedImageForIcon:(id)arg1;
- (id)imageForReflection;
- (void)setDisplayedIconImage:(id)arg1;
- (struct CGAffineTransform)transformToMakeIconBorderExpandToSizeOfDropGlow;
- (void)showDropGlow:(BOOL)arg1;
- (struct CGImage *)createComposedIconImageUsingContext:(struct CGContext *)arg1;
- (struct CGRect)frameForIconOverlay;
- (void)placeGhostlyImageView;
- (void)setGhostly:(BOOL)arg1 requester:(int)arg2;
- (void)setPartialGhostly:(float)arg1 requester:(int)arg2;
- (id)progressBar;
- (id)iconBorderView;
- (id)displayName;
- (id)representation;
- (BOOL)matchesRepresentation:(id)arg1;
- (id)folder;
- (id)description;
- (void)launch;
- (BOOL)allowsTapWhileEditing;
- (BOOL)delaysUnhighlightWhenTapped;
- (double)grabDurationForEvent:(id)arg1;
- (void)_updateBadgeValue;
- (void)_updateProgressBar;
- (void)noteContainedIconsAdded:(id)arg1 removed:(id)arg2;
- (void)noteContainedIconBadgeChanged:(id)arg1;
- (void)noteContainedIconImageChanged:(id)arg1;
- (void)noteContainedIconDownloadingStateChanged:(id)arg1;
- (void)noteIcon:(id)arg1 isAnimatingIn:(BOOL)arg2;
- (struct CGSize)_sizeOfMiniIconGrid;
- (struct CGSize)_sizeOfMiniIconGridWithRows:(unsigned int)arg1;
- (id)_miniIconGrid;
- (id)_miniIconGridFromRow:(unsigned int)arg1 toRow:(unsigned int)arg2;
- (unsigned int)_maxIcons;
- (unsigned int)_firstSkippedIconIndex;
- (unsigned int)_numberOfExcessIcons;
- (unsigned int)_firstIconIndexForRow:(unsigned int)arg1;
- (id)miniImageForIcon:(id)arg1;
- (struct CGRect)_rectForMiniIconAtIndex:(unsigned int)arg1 firstRow:(unsigned int)arg2;
- (void)_scrollAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_delegateCloseFolderAnimated:(BOOL)arg1;
- (void)_delegateOpenFolder:(id)arg1 animated:(BOOL)arg2;

@end

