/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBGestureMotionParams : NSObject
{
    float _animationDistance;
    float _commitDistance;
    float _accelerationThreshold;
    float _accelerationPower;
    int _requiredDirectionality;
    float _defaultHandSize;
    float _handSizeCompensationPower;
    float _sigmoidInflection_mmps;
    float _sigmoidAmplitude;
    float _sigmoidSharpness;
}

- (float)computeNonlinearSpeedGain:(float)arg1;
- (float)computeHandSizeCompensationGain:(float)arg1;
- (void)clear;
@property(nonatomic) float handSizeCompensationPower; // @synthesize handSizeCompensationPower=_handSizeCompensationPower;
@property(nonatomic) float defaultHandSize; // @synthesize defaultHandSize=_defaultHandSize;
@property(nonatomic) int requiredDirectionality; // @synthesize requiredDirectionality=_requiredDirectionality;
@property(nonatomic) float accelerationPower; // @synthesize accelerationPower=_accelerationPower;
@property(nonatomic) float accelerationThreshold; // @synthesize accelerationThreshold=_accelerationThreshold;
@property(nonatomic) float commitDistance; // @synthesize commitDistance=_commitDistance;
@property(nonatomic) float animationDistance; // @synthesize animationDistance=_animationDistance;

@end

