/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBHarmonicOscillator : NSObject
{
    float A;
    float Z;
    float k;
    float dk;
    float mink;
    float m;
    float dm;
    float minm;
    float phi;
    float b;
    float psi0;
    float gamma;
    float psi1;
}

- (id)init;
- (void)setSpringConstant:(float)arg1;
@property(nonatomic) float mass; // @synthesize mass=m;
@property(nonatomic) float phase; // @synthesize phase=phi;
@property(nonatomic) float dragCoefficient; // @synthesize dragCoefficient=b;
- (void)updateParameters;
- (float)amplitudeForElapsedTime:(double)arg1;
@property(readonly, nonatomic) float dampedFrequency; // @synthesize dampedFrequency=psi1;
@property(readonly, nonatomic) float dampingFactor; // @synthesize dampingFactor=gamma;
@property(readonly, nonatomic) float naturalFrequency; // @synthesize naturalFrequency=psi0;
@property(nonatomic) float minimumMass; // @synthesize minimumMass=minm;
@property(nonatomic) float massDecay; // @synthesize massDecay=dm;
@property(nonatomic) float minimumSpringStrength; // @synthesize minimumSpringStrength=mink;
@property(nonatomic) float springDecay; // @synthesize springDecay=dk;
@property(nonatomic) float springStrength; // @synthesize springStrength=k;
@property(nonatomic) float endingAmplitude; // @synthesize endingAmplitude=Z;
@property(nonatomic) float startingAmplitude; // @synthesize startingAmplitude=A;

@end

