/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBHandMotionExtractor : NSObject
{
    CDStruct_812d5f7b _pixel_deltas;
    CDStruct_812d5f7b _smoothed_deltas;
    CDStruct_812d5f7b _all_pixel_deltas;
    float _smoothed_translation_speed;
    float _nondominant_axes_ratio;
    float _farthest_finger_separation;
    int _num_non_edge_touches;
}

- (void)clear;
- (void)extractHandMotionForInnermostPath:(CDStruct_a924d358 *)arg1 outermostPath:(CDStruct_a924d358 *)arg2 activeTouchesCount:(unsigned int)arg3;
@property(readonly, nonatomic) float farthestFingerSeparation; // @synthesize farthestFingerSeparation=_farthest_finger_separation;
@property(readonly, nonatomic) CDStruct_812d5f7b averageVelocities; // @synthesize averageVelocities=_smoothed_deltas;
@property(readonly, nonatomic) CDStruct_812d5f7b allPixelDeltas; // @synthesize allPixelDeltas=_all_pixel_deltas;
@property(readonly, nonatomic) CDStruct_812d5f7b pixelDeltas; // @synthesize pixelDeltas=_pixel_deltas;

@end

