/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIconBadge.h"

@class UIImageView;

@interface SBIconImageBadge : SBIconBadge
{
    UIImageView *_badgeImageView;
}

- (id)initWithImage:(id)arg1;
- (void)dealloc;

@end

