/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSString;

@interface SBIconBadge : UIView
{
    NSString *_badge;
    struct CGSize _badgeContentSize;
    BOOL _highlighted;
    float _brightness;
}

+ (float)badgeLabelVerticalOffset;
+ (id)iconBadgeWithBadgeString:(id)arg1;
- (id)initWithBadgeString:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setHightlighted:(BOOL)arg1;
- (void)drawBackgroundImage;
- (void)drawRect:(struct CGRect)arg1;
- (void)darken:(float)arg1;

@end

