/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBInvitationAlertItem : SBAlertItem
{
    NSString *_title;
    NSString *_organizer;
    double _startDate;
    double _endDate;
    int _eventId;
    BOOL _allDay;
    BOOL _floats;
    int _count;
    int _status;
}

+ (id)activeInvitationAlertItems;
+ (void)_addActiveItem:(id)arg1;
+ (void)_removeActiveItem:(id)arg1;
+ (void)registerForAlerts;
+ (void)_invalidateFormatters;
+ (void)_significantTimeChange;
+ (void)_localeChanged;
+ (struct __CFDateFormatter *)_customFormatter;
- (id)init;
- (id)initWithCount:(int)arg1;
- (id)initWithTitle:(id)arg1 organizerName:(id)arg2 startDate:(double)arg3 endDate:(double)arg4 floats:(BOOL)arg5 allDay:(BOOL)arg6 eventId:(int)arg7 status:(int)arg8;
- (void)dealloc;
- (void)didDeactivateForReason:(int)arg1;
- (int)eventId;
- (int)count;
- (int)status;
- (id)_stringForTime:(CDStruct_79f9e052)arg1;
- (id)_stringForDateTime:(CDStruct_79f9e052)arg1 timeZone:(struct __CFTimeZone *)arg2;
- (id)_dateString;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)lockLabel;
- (void)didPresentAlertView:(id)arg1;
- (void)revealEvent;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)performUnlockAction;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)willShowInAwayItems;
- (void)_playPresentationSound;

@end

