/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIImageView.h"

@interface SBLinenNotchView : UIImageView
{
}

+ (id)_keyForNotchInfo:(CDStruct_d18cc6b1)arg1;
+ (id)_imageForNotchInfo:(CDStruct_d18cc6b1)arg1;
+ (id)notchForNotchInfo:(CDStruct_d18cc6b1)arg1;
- (id)initWithFrame:(struct CGRect)arg1 notchInfo:(CDStruct_d18cc6b1)arg2;
- (void)setNotchInfo:(CDStruct_d18cc6b1)arg1;

@end

