/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSString;

@interface SBMMSDelayedDownloadAlertItem : SBAlertItem
{
    NSString *_fromAddress;
    int _messageCount;
}

- (void)dealloc;
- (void)setMessage:(id)arg1;
- (void)setMessageCount:(int)arg1;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)_showNetworkPrefs;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;

@end

