/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBFlippyAlertItem.h"

#import "UIAlertViewDelegate-Protocol.h"

@class MPAudioDeviceController, UIButton;

@interface SBNowPlayingAlertItem : SBFlippyAlertItem <UIAlertViewDelegate>
{
    unsigned int _beganSeeking:1;
    unsigned int _deferLayout:1;
    unsigned int _needsLayout:1;
    MPAudioDeviceController *_audioDeviceController;
    UIButton *_prevButton;
    UIButton *_playButton;
    UIButton *_nextButton;
}

- (id)init;
- (void)dealloc;
- (id)newCenteredLabel:(BOOL)arg1;
- (void)_updateLabelWithTag:(int)arg1 text:(id)arg2 faded:(BOOL)arg3 cursor:(float *)arg4 sheet:(id)arg5;
- (void)updateInformation;
- (id)_newButtonWithImage:(id)arg1 action:(SEL)arg2 tag:(int)arg3;
- (Class)frontAlertSheetClass;
- (Class)backAlertSheetClass;
- (id)newFrontAlertSheet;
- (id)newBackAlertSheet;
- (void)willActivate;
- (void)willDeactivateForReason:(int)arg1;
- (BOOL)allowMenuButtonDismissal;
- (BOOL)dismissOnLock;
- (BOOL)dismissOnAlertActivation;
- (void)configureFront:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)audioRoutingPicker:(id)arg1 didSelectRouteAtIndex:(int)arg2;
- (void)willPresentAlertView:(id)arg1;
- (void)didPresentAlertView:(id)arg1;
- (void)_playPauseButtonAction:(id)arg1;
- (void)_changeTrackButtonDown:(id)arg1;
- (void)_changeTrackButtonUp:(id)arg1;
- (void)_changeTrackButtonEndSeek:(id)arg1;
- (void)_changeTrackButtonTouchPause:(id)arg1;
- (void)_volumeChange:(id)arg1;
- (void)_registerForNowPlayingNotifications;
- (void)_unregisterForNowPlayingNotifications;
- (void)_registerForVolumeNotifications;
- (void)_unregisterForVolumeNotifications;
- (void)_nowPlayingChanged:(id)arg1;
- (void)_systemVolumeChanged:(id)arg1;
- (void)_registerForMuteNotifications;
- (void)_unregisterForMuteNotifications;
- (void)_systemMuteStatusChanged:(id)arg1;
- (void)audioDeviceControllerAudioRoutesChanged:(id)arg1;
- (void)audioDeviceControllerMediaServerDied:(id)arg1;

@end

