/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBPointTracker : NSObject
{
    int pindex;
    int pcount;
    struct {
        struct CGPoint point;
        double timestamp;
    } points[10];
}

- (id)init;
- (void)dealloc;
- (void)addPoint:(struct CGPoint)arg1;
- (void)clear;
@property(readonly, nonatomic) struct CGPoint velocity;
- (struct CGPoint)pointIgnoringInterval:(double)arg1;
- (struct CGPoint)averageInInterval:(double)arg1;
- (struct CGPoint)cumulativeMovementInInterval:(double)arg1;

@end

