/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "APSConnectionDelegate-Protocol.h"
#import "SBRemoteLocalNotificationAlertDelegate-Protocol.h"

@class NSMutableDictionary, NSString;

@interface SBRemoteNotificationServer : NSObject <APSConnectionDelegate, SBRemoteLocalNotificationAlertDelegate>
{
    NSMutableDictionary *_bundleIdentifiersToClients;
    NSMutableDictionary *_environmentsToConnections;
    NSString *_lastNotificationReceivedBundleIdentifier;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)run;
- (void)remoteLocalNotificationAlertShouldLaunch:(id)arg1 forApplication:(id)arg2;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)noteApplicationFinishedLaunching:(id)arg1;
- (void)connection:(id)arg1 didReceiveMessageForTopic:(id)arg2 userInfo:(id)arg3;
- (id)lastNotificationReceivedBundleIdentifier;
- (id)allAppEnabledTypeValues;
- (id)allSettingsEnabledTypeValues;
- (void)calculateTopics;
- (void)registerApplication:(id)arg1 forEnvironment:(id)arg2 withTypes:(int)arg3;
- (void)unregisterApplication:(id)arg1;
- (int)getEffectiveEnabledTypesForApplication:(id)arg1;
- (BOOL)isSystemwideEnabled;
- (void)setSystemwideEnabled:(BOOL)arg1;
- (BOOL)hasRegisteredBundleIdentifiers;
- (void)setSettingsTypes:(int)arg1 forBundleIdentifier:(id)arg2;
- (id)getMessageUserInfoForBundleIdentifier:(id)arg1;

@end

