/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol SBRemoteLocalNotificationAlertDelegate
- (void)remoteLocalNotificationAlertShouldLaunch:(id)arg1 forApplication:(id)arg2;

@optional
- (void)remoteLocalNotificationAlertShouldSnooze:(id)arg1 forApplication:(id)arg2;
@end

