/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class SBKeyboard, SBNoResultsView, SBRoundedCornersView, UILabel, UISearchBar, UITableView;

@interface SBSearchView : UIView
{
    SBRoundedCornersView *_roundedCornersView;
    UISearchBar *_searchBar;
    UITableView *_tableView;
    SBKeyboard *_keyboard;
    UILabel *_noResultsLabel;
    SBNoResultsView *_noResultsView;
    UIView *_rootView;
    UIView *_contentView;
    BOOL _isKeyboardVisible;
    BOOL _isKeyboardAnimatingRotation;
    BOOL _showSearchKeyWhenAnimatingKeyboard;
    BOOL _keyboardWasMinimizedWhenAnimationStarted;
    BOOL _hidesEmptyTableFooter;
}

+ (double)keyboardAnimationDuration;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withContent:(id)arg2 onWallpaper:(id)arg3;
- (BOOL)_initializeKeyboardIfNotBricked;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)setFrame:(struct CGRect)arg1;
- (void)scrollViewIsScrollingHorizontally;
- (void)setShowsNoResultsView:(BOOL)arg1;
- (void)layoutCornerView;
- (void)setHidesEmptyTableFooter:(BOOL)arg1;
- (float)_footerHeight;
- (void)layoutFooterView;
- (void)_layoutNoResultsView;
- (Class)tableViewClass;
- (Class)searchBarClass;
- (BOOL)isKeyboardMinimized;
- (BOOL)isKeyboardVisible;
- (void)_keyboardWillShow:(id)arg1;
- (void)_keyboardDidHide:(id)arg1;
- (void)setShowsKeyboard:(BOOL)arg1 animated:(BOOL)arg2;
- (void)keyboardAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_fixUpRespondersAndPreheat;
- (void)setShowingNoResultsText:(BOOL)arg1;
- (void)setShowsSearchKeyWhenAnimatingKeyboard:(BOOL)arg1;
- (void)_setDistantContentViewTransform;
- (void)_resetContentViewTransform;
- (void)scatter:(BOOL)arg1 startTime:(double)arg2;
- (void)scatterAnimationDidStop;
- (void)unscatter:(BOOL)arg1 startTime:(double)arg2;
- (void)unscatterAnimationDidStop;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
@property(readonly, nonatomic) UIView *roundedCornersView; // @synthesize roundedCornersView=_roundedCornersView;
@property(retain, nonatomic) UIView *rootView; // @synthesize rootView=_rootView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(readonly, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;

@end

