/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBSIMToolkitGetInputDisplay.h"

@interface SBSIMToolkitOneShotGetInputDisplay : SBSIMToolkitGetInputDisplay
{
}

- (BOOL)textField:(id)arg1 shouldInsertText:(id)arg2 replacingRange:(struct _NSRange)arg3;

@end

