/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBSIMToolkitTextAlertDisplay.h"

@interface SBSIMToolkitSetUpCallDisplay : SBSIMToolkitTextAlertDisplay
{
}

+ (id)newTopBarForInstance:(id)arg1;
+ (id)newBottomBarForInstance:(id)arg1;
- (void)dismiss:(id)arg1;
- (id)_activeCalls;
- (void)dial:(id)arg1;
- (id)alertText;

@end

