/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlert.h"

@class AVController, AVQueue, NSString, NSTimer;

@interface SBSIMToolkitAlert : SBAlert
{
    BOOL _needsResponse;
    NSTimer *_timeoutTimer;
    NSString *_tone;
    AVController *_avController;
    AVQueue *_avQueue;
    BOOL _interruptedAudio;
}

+ (struct __CTServerConnection *)simToolkitServerConnection;
+ (BOOL)wantsNextUserEvent;
+ (void)userEventOccurred;
+ (void)setCurrentAlert:(id)arg1;
+ (id)currentAlert;
+ (void)dismissCurrentAlert;
+ (void)test;
+ (void)_idleScreenShown:(id)arg1;
+ (void)_stopSTKMonitor;
+ (void)_startSTKMonitor;
+ (void)_restartMonitor;
+ (void)registerForAlerts;
- (void)setNeedsResponse:(BOOL)arg1;
- (BOOL)needsResponse;
- (void)sendResponse:(struct __CFString *)arg1 withString:(id)arg2;
- (void)sendResponse:(struct __CFString *)arg1 withBool:(BOOL)arg2;
- (void)sendResponse:(struct __CFString *)arg1;
- (unsigned long)_soundIDForTone:(struct __CFString *)arg1;
- (void)_setAudioInterrupted:(BOOL)arg1;
- (void)_playbackDidEnd:(id)arg1;
- (void)playRingtoneWithIdentifier:(id)arg1 loop:(BOOL)arg2;
- (void)_stopTone:(id)arg1;
- (BOOL)sendResponseUponDisplay;
- (BOOL)dismissesAfterNextEvent;
- (BOOL)oneShotInputEntry;
- (void)dealloc;
- (BOOL)allowsEventOnlySuspension;
- (void)deactivate;
- (void)_playTone:(struct __CFString *)arg1 forDuration:(float)arg2;
- (struct __CFString *)toolkitAlertType;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)clearTimeoutTimer;
- (BOOL)_delayEnabled;
- (void)restartTimeoutTimer:(float)arg1;
- (void)startTimeoutTimerIfNecessary;
- (void)displayDidTimeout;

@end

