/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@class SBTextDisplayView, UIScrollView;

@interface SBSIMToolkitTextAlertDisplay : SBSlidingAlertDisplay
{
    SBTextDisplayView *_contentView;
    UIScrollView *_scroller;
}

+ (id)newTopBarForInstance:(id)arg1;
+ (id)newBottomBarForInstance:(id)arg1;
- (void)dealloc;
- (void)leftNavigationButtonPressed;
- (void)rightNavigationButtonPressed;
- (void)adjustScrollerFrame;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)alertText;
- (void)layoutForInterfaceOrientation:(int)arg1;
- (BOOL)showsDesktopImage;
- (void)setMiddleContentAlpha:(float)arg1;
- (void)displayDidTimeout;
- (void)alertDisplayWillBecomeVisible;
- (void)accept:(id)arg1;
- (void)dismiss:(id)arg1;
- (void)dismiss;

@end

