/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class CKMessage, NSString;

@interface SBSMSAlertItem : SBAlertItem
{
    CKMessage *_message;
    int _alignment;
    BOOL _alignmentHasBeenSet;
    BOOL _displayingEntireMessage;
    BOOL _playedSound;
    NSString *_name;
}

+ (void)stopPlayingCurrentAlertTone;
+ (void *)lastMessageSender;
+ (void)setLastMessageSender:(void *)arg1;
+ (BOOL)shouldPlayMessageReceived;
+ (void)playMessageReceived;
+ (unsigned long)customAlertToneForSender:(void *)arg1;
+ (void)showSMSPreviewPrefChanged;
+ (void)defaultAlertTonePrefChanged;
+ (BOOL)_showSMSPreview;
+ (BOOL)shouldHideSMSPreview;
- (void)dealloc;
- (void)_tag;
- (void)_untag;
- (void)_deactivateAllTaggedSMSAlertItems;
- (void)willActivate;
- (void)didDeactivateForReason:(int)arg1;
- (void)willRelockForButtonPress:(BOOL)arg1;
- (void)setMessage:(id)arg1;
- (void)willPresentAlertView:(id)arg1;
- (id)address;
- (id)name;
- (BOOL)senderIsVoicemail;
- (BOOL)hasAttachments;
- (id)messageText;
- (id)alertImageData;
- (int)_groupID;
- (void)reply;
- (Class)alertSheetClass;
- (id)alertSheet;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (int)bodyTextAlignmentForAlertSheet:(id)arg1 displayedLineCount:(int)arg2;
- (void)performUnlockAction;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (id)lockLabel;
- (BOOL)willShowInAwayItems;
- (BOOL)shouldShowInEmergencyCall;
- (BOOL)shouldShowInLockScreen;
- (int)alertItemNotificationType;
- (id)alertItemNotificationDate;
- (id)alertItemNotificationSender;

@end

