/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBSMSManager : NSObject
{
}

+ (BOOL)carrierSMSReceiveOnlyEnabled;
+ (id)sharedSMSManager;
- (void)messageSent:(id)arg1;
- (void)messageSendError:(id)arg1;
- (void)messageReceived:(id)arg1;
- (id)init;
- (void)redisplayAllMessagesForCarrierSMSReceiveOnlyMode;
- (void)dealloc;
- (id)badgeNumberOrString;
- (void)setBadgeNumberOrString:(id)arg1;
- (BOOL)isShowingSendFailure;
- (void)markMessageAsRead:(id)arg1;
- (void)deleteMessage:(id)arg1 deleteConversationIfEmpty:(BOOL)arg2;
- (void)updateSMSBadges;

@end

