/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBUSSDAlert.h"

@interface SBSMSClass0Alert : SBUSSDAlert
{
}

+ (void)registerForAlerts;
- (void)_unregisterForNotifications;
- (void)_registerForNotifications;
- (id)initWithString:(id)arg1;

@end

