/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UISnapshotView.h"

@interface SBStretchColumnView : UISnapshotView
{
    struct CGRect m_originalFrame;
    float m_factor;
    struct CGImage *m_image;
}

- (id)initWithFrame:(struct CGRect)arg1 targetView:(id)arg2;
@property(nonatomic) float factor; // @synthesize factor=m_factor;
@property(nonatomic) struct CGRect originalFrame; // @synthesize originalFrame=m_originalFrame;

@end

