/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "RadiosPreferencesDelegate-Protocol.h"

@class NSDateFormatter, NSString, NSTimer, RadiosPreferences;

@interface SBStatusBarDataManager : NSObject <RadiosPreferencesDelegate>
{
    struct {
        char itemIsEnabled[22];
        char timeString[64];
        int gsmSignalStrengthRaw;
        int gsmSignalStrengthBars;
        char serviceString[100];
        char serviceImageBlack[100];
        char serviceImageSilver[100];
        char operatorDirectory[1024];
        unsigned int serviceContentType;
        int wifiSignalStrengthRaw;
        int wifiSignalStrengthBars;
        unsigned int dataNetworkType;
        int batteryCapacity;
        unsigned int batteryState;
        char notChargingString[150];
        int bluetoothBatteryCapacity;
        int thermalColor;
        unsigned int thermalSunlightMode:1;
        unsigned int slowActivity:1;
        char activityDisplayId[256];
        unsigned int bluetoothConnected:1;
        unsigned int displayRawGSMSignal:1;
        unsigned int displayRawWifiSignal:1;
    } _data;
    int _actions;
    char _itemIsEnabled[22];
    char _itemIsCloaked[22];
    int _updateBlockDepth;
    BOOL _dataChangedSinceLastPost;
    NSDateFormatter *_timeItemDateFormatter;
    NSTimer *_timeItemTimer;
    NSString *_timeItemTimeString;
    RadiosPreferences *_radiosPrefs;
    BOOL _cellRadio;
    BOOL _registered;
    BOOL _simError;
    BOOL _simulateInCallStatusBar;
    NSString *_serviceString;
    NSString *_serviceImageBlack;
    NSString *_serviceImageSilver;
    NSString *_operatorDirectory;
    BOOL _showsActivityIndicatorOnHomeScreen;
    int _thermalColor;
    BOOL _thermalSunlightMode;
    NSString *_recordingAppString;
    BOOL _showingNotChargingItem;
    NSString *_notChargingString;
}

+ (id)sharedDataManager;
- (id)init;
- (void)dealloc;
- (void)beginUpdateBlock;
- (void)endUpdateBlock;
- (void)setStatusBarItem:(int)arg1 enabled:(BOOL)arg2;
- (void)setStatusBarItem:(int)arg1 cloaked:(BOOL)arg2;
- (void)updateStatusBarItem:(int)arg1;
- (void)sendStatusBarActions:(int)arg1;
- (void)enableLock:(BOOL)arg1 time:(BOOL)arg2;
- (void)setShowsActivityIndicatorOnHomeScreen:(BOOL)arg1;
- (void)setTelephonyAndBluetoothItemsCloaked:(BOOL)arg1;
- (void)setAllItemsExceptBatteryCloaked:(BOOL)arg1;
- (void)setThermalColor:(int)arg1 sunlightMode:(BOOL)arg2;
- (void)_initializeData;
- (void)_dataChanged;
- (void)_postData;
- (void)_updateTimeString;
- (void)_updateTimeItem;
- (void)_updateAirplaneMode;
- (void)_updateSignalStrengthItem;
- (void)_updateServiceItem;
- (void)_updateDataNetworkItem;
- (void)_updateBatteryItem;
- (void)_updateBatteryPercentItem;
- (void)_updateNotChargingItem;
- (void)_updateBluetoothItem;
- (void)_updateBluetoothBatteryItem;
- (void)_updateTTYItem;
- (void)_updateVPNItem;
- (void)_updateCallForwardingItem;
- (void)_updateActivityItem;
- (void)_updatePlayItem;
- (void)_updateLocationItem;
- (void)_updateRotationLockItem;
- (void)_updateThermalColorItem;
- (void)_registerForNotifications;
- (void)_significantTimeOrLocaleChange;
- (void)_didWakeFromSleep;
- (void)_batteryStatusChange;
- (void)_notChargingStatusChange;
- (void)_operatorChange;
- (void)_signalStrengthChange;
- (void)_ttyChange;
- (void)_callForwardingChange;
- (void)_vpnChange;
- (void)_dataNetworkChange;
- (void)airplaneModeChanged;
- (void)_bluetoothChange;
- (void)_bluetoothBatteryChange;
- (void)_locationStatusChange;
- (void)_rotationLockChange;
- (void)_configureTimeItemDateFormatter;
- (void)_stopTimeItemTimer;
- (void)_restartTimeItemTimer;
- (BOOL)_shouldShowNotChargingItem;
- (void)_updateNotChargingItemAfterDelay;
- (void)_updateTelephonyState;
- (void)toggleSimulatesInCallStatusBar;
- (id)_displayStringForSIMStatus:(id)arg1;
- (id)_displayStringForRegistrationStatus:(int)arg1;
- (void)_getBlackImageName:(id *)arg1 silverImageName:(id *)arg2 directory:(id *)arg3 forFakeCarrier:(id)arg4;
- (BOOL)_getBlackImageName:(id *)arg1 silverImageName:(id *)arg2 directory:(id *)arg3 forOperator:(id)arg4 statusBarCarrierName:(id *)arg5;

@end

