/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBTVOutController : NSObject
{
    int _tvOutMode;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)setIntialTVModeIfNeeded;
- (void)updateLayerKitSettings;
- (void)updateSettings;
@property(readonly, nonatomic) BOOL isTVSignalTypeDigital;
@property(nonatomic) int tvOutMode; // @synthesize tvOutMode=_tvOutMode;

@end

