/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBTVOutController.h"

@interface SBTVOutController (private)
- (void)_handleIapServerConnectionDied;
- (void)_tetherSettingChanged:(id)arg1;
- (void)startListeningForSettingsChanges;
- (void)stopListeningForSettingsChanges;
@end

