/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@interface SBUIRootView : UIView
{
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setAlpha:(float)arg1;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;

@end

