/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlert.h"

@class CNFConferenceController, CNFDisplayController, NSString, NSURL;

@interface SBVideoAlert : SBAlert
{
    CNFConferenceController *_conferenceController;
    NSURL *_inviter;
    CNFDisplayController *_displayController;
    NSString *_conferenceID;
}

- (id)initWithConferenceController:(id)arg1 inviter:(id)arg2 conferenceID:(id)arg3;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)inviterCanceledConference;
- (id)conferenceController;
- (id)inviter;
- (id)displayController;
- (id)conferenceID;
- (void)handleLock:(BOOL)arg1;
- (void)dealloc;

@end

