/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSDate, NSString;

@interface SBVoiceMailAlertItem : SBAlertItem
{
    BOOL _isForVisualVoicemail;
    unsigned int _recordUID;
    NSString *_title;
    NSString *_body;
    NSString *_rawSender;
    NSDate *_date;
}

- (void)dealloc;
- (BOOL)isForVisualVoicemail;
- (void)setIsVisualVoicemail:(BOOL)arg1 recordUID:(unsigned int)arg2;
- (BOOL)willShowInAwayItems;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;
- (BOOL)dismissOnLock;
- (id)lockLabel;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)bodyText;
- (void)setBodyText:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)performUnlockAction;
- (void)_performAppropriateListenAction;
- (void)_launchPhoneAndDisplayVoicemailRecord:(int)arg1;
- (int)alertItemNotificationType;
- (id)alertItemNotificationDate;
- (id)alertItemNotificationSender;
@property(retain, nonatomic) NSString *rawSender; // @synthesize rawSender=_rawSender;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;

@end

