/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertItem.h"

@class NSArray, NSString;

@interface SBWiFiTrustAlertItem : SBAlertItem
{
    NSString *_displayName;
    NSString *_networkName;
    NSArray *_certificateArray;
    BOOL _sentResponse;
}

- (Class)alertSheetClass;
- (id)initWithCertificateArray:(id)arg1 networkName:(id)arg2;
- (void)dealloc;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)didDeactivateForReason:(int)arg1;
- (BOOL)dismissOnLock;
- (BOOL)allowMenuButtonDismissal;
- (void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2;

@end

