/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIAlertView.h"

@interface SMSAlertSheet : UIAlertView
{
    BOOL _showingTagline;
    BOOL _showingImage;
}

- (void)layout;
- (void)setImageData:(id)arg1;
- (BOOL)showingImage;
- (void)updateTagline;
- (void)layoutAnimated:(BOOL)arg1;

@end

