/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITextInputTraits-Protocol.h"

@protocol UIKeyInput <UITextInputTraits>
- (BOOL)hasText;
- (void)insertText:(id)arg1;
- (void)deleteBackward;
@end

