/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol UITextInputTraits <NSObject>
@property(nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;

@optional
@property(nonatomic) BOOL enablesReturnKeyAutomatically;
@property(nonatomic) int returnKeyType;
@property(nonatomic) int keyboardAppearance;
@property(nonatomic) int keyboardType;
@property(nonatomic) int autocorrectionType;
@property(nonatomic) int autocapitalizationType;
@end

